# Generated by Django 5.2.14 on 2026-05-19 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du parc')),
            ],
            options={
                'verbose_name': 'Parc',
                'verbose_name_plural': 'Parcs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('spot_code', models.CharField(max_length=20, verbose_name='Code place')),
                ('old_chassis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ancien châssis')),
                ('new_chassis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nouveau châssis')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('park', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.park', verbose_name='Parc')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code place')),
                ('status', models.CharField(choices=[('libre', 'Libre'), ('occupé', 'Occupé')], default='libre', max_length=10, verbose_name='Statut')),
                ('chassis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de châssis')),
                ('x', models.FloatField(default=0, verbose_name='Position X')),
                ('y', models.FloatField(default=0, verbose_name='Position Y')),
                ('w', models.FloatField(default=64, verbose_name='Largeur')),
                ('h', models.FloatField(default=40, verbose_name='Hauteur')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='parking.park', verbose_name='Parc')),
            ],
            options={
                'verbose_name': 'Place de parking',
                'verbose_name_plural': 'Places de parking',
                'ordering': ['park', 'code'],
                'unique_together': {('park', 'code')},
            },
        ),
    ]
